import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center`}
      >
        <a id="top" className=""></a>
        <header className="sticky top-0 z-100 w-full bg-[#dddddd]">
          <div className="text-xl m-[1em]">Gracie Armour's Portfolio</div>
        </header>

        {children}

        <footer className="w-full border-t-2">
        </footer>
      </body>
    </html>
  );
}
