/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Projects {
  collaborators: Generated<string>;
  demo: Generated<string>;
  description: string;
  id: Generated<number>;
  made_for: Generated<string>;
  project_language: string;
  project_link: Generated<string>;
  title: string;
  type: string;
}

export interface DB {
  projects: Projects;
}
